### ISSUE TITLE
.txt

### ISSUE THREAD

**Issue by Tyrolyean1** [xKippi/Snake#2]
As discribed in the last issue, you nsme your files with .txt for the beginning programmers. So why don't you do that with your license? I would recommend you naming all of them .md, because even beginners understand it.

**Comment by xKippi** [comment]
1. I only named the readme file .txt, because i want that any kind of beginner can open it.
2. I thing most beginners don't care about the licence and so it does not matter if they don't know how to open it.
3. Thank you for your suggestion I'll think about it.

**Comment by Tyrolyean1** [comment]
You shouldn't ignore the meaning of your license.
A penetrant owner can possibly loose his rights...
Think about it.
P.S. this is not a duplicate entry

**Comment by xKippi** [comment]
If I would rename the readme.txt file to just readme would this be acceptable for you?

PS: This is not a duplicate entry, but you already reported this issue...

**Comment by Tyrolyean1** [comment]
I reported a fairly simmilar issue but they aren't the same.
I think a bit of consistency would be pretty good.
To start thinking diffrently during a Project is a faitly common mistake i made pretty often,
for example the names of variables should look pretty simmilar, but in my programs they never did.

**Comment by xKippi** [comment]
Ok i renamed it. I think this issue is "fixed" now.

**Comment by Tyrolyean1** [comment]
Congratulations
